export const REQUEST_PORTFOLIO = "REQUEST_PORTFOLIO";
export const DISPLAY_PORTFOLIO = "DISPLAY_PORTFOLIO";
export const REQUEST_REPOS = "REQUEST_REPOS";
export const DISPLAY_REPOS = "DISPLAY_REPOS";
